<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0</TargetFrameworks>
        <Platforms>AnyCPU</Platforms>
        <LangVersion>latest</LangVersion>
        <NoWarn>NU1701</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="Scripts\DNS\PoshACME\Posh-ACME-Wrapper.ps1" />
        <None Remove="Scripts\Internal\Script-Wrapper.ps1" />
        <None Remove="THIRD_PARTY_LICENSES.txt" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="Scripts\DNS\PoshACME\Posh-ACME-Wrapper.ps1">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="Scripts\Internal\Script-Wrapper.ps1">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="THIRD_PARTY_LICENSES.txt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>


    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.3.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" />
        <PackageReference Include="SimpleImpersonation" Version="4.2.0" />
        <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.6.1" />
        <PackageReference Include="System.Management.Automation" Version="7.6.1" />
    </ItemGroup>


    <ItemGroup>
        <ProjectReference Include="..\Certify.Models\Certify.Models.csproj" />
        <ProjectReference Include="..\Certify.Shared\Certify.Shared.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Certify.Tests.DeploymentTasks" />
    </ItemGroup>


    <ItemGroup>
        <None Update="Assets\public_suffix_list.dat">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Assets\rdap_dns.json.dat">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Scripts\AutoUpdate\AutoUpdate.ps1">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Scripts\Common\index.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Scripts\Common\MSExchangeEnableServices.ps1">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Scripts\Common\RDPGatewayServices.ps1">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Scripts\Common\RDPListenerService.ps1">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Scripts\Common\WebManagementService.ps1">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Scripts\DNS\ExampleDNSCreate.bat">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Scripts\DNS\ExampleDNSDelete.bat">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Scripts\Python\dns_helper.py">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Scripts\Python\dns_helper_util.py">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Scripts\Web.config\readme.txt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Scripts\Web.config\Web.alt0.config">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Scripts\Web.config\Web.alt1.config">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Scripts\Web.config\Web.alt2.config">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Scripts\Web.config\Web.alt3..config">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Scripts\Web.config\Web.alt4.config">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
