//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Certify.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Certify.UI.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Language Translator:  的本地化字符串。
        /// </summary>
        public static string About_LanguageTranslator {
            get {
                return ResourceManager.GetString("About_LanguageTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for Updates.. 的本地化字符串。
        /// </summary>
        public static string AboutControl_CheckForUpdateButton {
            get {
                return ResourceManager.GetString("AboutControl_CheckForUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter Key.. 的本地化字符串。
        /// </summary>
        public static string AboutControl_EnterKey {
            get {
                return ResourceManager.GetString("AboutControl_EnterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register 的本地化字符串。
        /// </summary>
        public static string AboutControl_Register {
            get {
                return ResourceManager.GetString("AboutControl_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Registered 的本地化字符串。
        /// </summary>
        public static string AboutControl_RegistrationTypeLabel {
            get {
                return ResourceManager.GetString("AboutControl_RegistrationTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Feedback 的本地化字符串。
        /// </summary>
        public static string AboutControl_SendFeedback {
            get {
                return ResourceManager.GetString("AboutControl_SendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Support 的本地化字符串。
        /// </summary>
        public static string AboutControl_Support {
            get {
                return ResourceManager.GetString("AboutControl_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This version is free for evaluation and is limited to managing up to 5 websites. To remove this limit please purchase a registration key. If you have previously donated please email apps@webprofusion.com with details of your sponsorship PayPal transaction to obtain a free key. This offer is also open to developers who have PRs accepted for this app on GitHub. 的本地化字符串。
        /// </summary>
        public static string AboutControl_TrialDetailLabel {
            get {
                return ResourceManager.GetString("AboutControl_TrialDetailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced 的本地化字符串。
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alert 的本地化字符串。
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ... 的本地化字符串。
        /// </summary>
        public static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Challenge 的本地化字符串。
        /// </summary>
        public static string Challenge {
            get {
                return ResourceManager.GetString("Challenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Challenge Error 的本地化字符串。
        /// </summary>
        public static string ChallengeError {
            get {
                return ResourceManager.GetString("ChallengeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comments:  的本地化字符串。
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure Auto Renew 的本地化字符串。
        /// </summary>
        public static string Configure_Auto_Renew {
            get {
                return ResourceManager.GetString("Configure_Auto_Renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Delete 的本地化字符串。
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discard Changes 的本地化字符串。
        /// </summary>
        public static string DiscardChanges {
            get {
                return ResourceManager.GetString("DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Address 的本地化字符串。
        /// </summary>
        public static string Email_Address {
            get {
                return ResourceManager.GetString("Email_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expires in {0} days 的本地化字符串。
        /// </summary>
        public static string ExpiryDateConverter_CertificateExpiresIn {
            get {
                return ResourceManager.GetString("ExpiryDateConverter_CertificateExpiresIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No current certificate. 的本地化字符串。
        /// </summary>
        public static string ExpiryDateConverter_NoCurrentCertificate {
            get {
                return ResourceManager.GetString("ExpiryDateConverter_NoCurrentCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 failed 的本地化字符串。
        /// </summary>
        public static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge multiple domains/certificates per site into one Managed Site 的本地化字符串。
        /// </summary>
        public static string ImportDlg_Merge {
            get {
                return ResourceManager.GetString("ImportDlg_Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are upgrading from an older version of Certify. This will create new Managed Sites which you can then edit to adjust the renewal settings etc. 的本地化字符串。
        /// </summary>
        public static string ImportDlg_OpComment {
            get {
                return ResourceManager.GetString("ImportDlg_OpComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Managed Sites 的本地化字符串。
        /// </summary>
        public static string ImportDlg_OpTitle {
            get {
                return ResourceManager.GetString("ImportDlg_OpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip Import 的本地化字符串。
        /// </summary>
        public static string ImportDlg_Skip {
            get {
                return ResourceManager.GetString("ImportDlg_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Certify - Import 的本地化字符串。
        /// </summary>
        public static string ImportDlg_Title {
            get {
                return ResourceManager.GetString("ImportDlg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In Progress 的本地化字符串。
        /// </summary>
        public static string In_Progress {
            get {
                return ResourceManager.GetString("In_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Certify （https://certifytheweb.com） 的本地化字符串。
        /// </summary>
        public static string LanguageAuthor {
            get {
                return ResourceManager.GetString("LanguageAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License Key 的本地化字符串。
        /// </summary>
        public static string LicenseKey {
            get {
                return ResourceManager.GetString("LicenseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get started by registering a new contact, then you can start requesting certificates. 的本地化字符串。
        /// </summary>
        public static string MainWindow_GetStartGuideWithNewCert {
            get {
                return ResourceManager.GetString("MainWindow_GetStartGuideWithNewCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IIS Was not detected on this server, important functionality will be unavailable. If you know IIS is installed and working on this server, please report this error to apps@webprofusion providing details of your server Operating System version and IIS versions 的本地化字符串。
        /// </summary>
        public static string MainWindow_IISNotAvailable {
            get {
                return ResourceManager.GetString("MainWindow_IISNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This will renew certificates for all auto-renewed items. Proceed? 的本地化字符串。
        /// </summary>
        public static string MainWindow_RenewAllConfirm {
            get {
                return ResourceManager.GetString("MainWindow_RenewAllConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  [Free Trial Version] 的本地化字符串。
        /// </summary>
        public static string MainWindow_TitleTrialPostfix {
            get {
                return ResourceManager.GetString("MainWindow_TitleTrialPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are using the trial version of this app. Please purchase a registration key to upgrade. See the Register option on the About tab. 的本地化字符串。
        /// </summary>
        public static string MainWindow_TrialLimitionReached {
            get {
                return ResourceManager.GetString("MainWindow_TrialLimitionReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visit download page now? 的本地化字符串。
        /// </summary>
        public static string MainWindow_VisitDownloadPage {
            get {
                return ResourceManager.GetString("MainWindow_VisitDownloadPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Managed Sites 的本地化字符串。
        /// </summary>
        public static string Managed_Sites {
            get {
                return ResourceManager.GetString("Managed_Sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto create/update IIS bindings (uses SNI) 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_AutoUpdateBinding {
            get {
                return ResourceManager.GetString("ManagedItemSettings_AutoUpdateBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bind to Specific IP: 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_BindIP {
            get {
                return ResourceManager.GetString("ManagedItemSettings_BindIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bind to Specific Port: 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_BindPort {
            get {
                return ResourceManager.GetString("ManagedItemSettings_BindPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ... 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_BrowseFolder {
            get {
                return ResourceManager.GetString("ManagedItemSettings_BrowseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot check challenges if IIS is not available. 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_CannotChallengeWithoutIIS {
            get {
                return ResourceManager.GetString("ManagedItemSettings_CannotChallengeWithoutIIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Certificate Revoked. 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_Certificate_Revoked {
            get {
                return ResourceManager.GetString("ManagedItemSettings_Certificate_Revoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The certificate file for this item has not been created yet. 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_CertificateNotReady {
            get {
                return ResourceManager.GetString("ManagedItemSettings_CertificateNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Certificate Path: [to be set] 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_CertificatePathEmpty {
            get {
                return ResourceManager.GetString("ManagedItemSettings_CertificatePathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WARNING: This certificate has been revoked. 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_CertificateRevokeWarning {
            get {
                return ResourceManager.GetString("ManagedItemSettings_CertificateRevokeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} challenge is only available for IIS versions 8+. 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_ChallengeNotAvailable {
            get {
                return ResourceManager.GetString("ManagedItemSettings_ChallengeNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Challenge Test Failed 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_ChallengeTestFailed {
            get {
                return ResourceManager.GetString("ManagedItemSettings_ChallengeTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Challenge Type: 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_ChallengeTypes {
            get {
                return ResourceManager.GetString("ManagedItemSettings_ChallengeTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration Check Failed:
        ///{0} 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_ConfigurationCheckFailed {
            get {
                return ResourceManager.GetString("ManagedItemSettings_ConfigurationCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration Checked OK 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_ConfigurationCheckOk {
            get {
                return ResourceManager.GetString("ManagedItemSettings_ConfigurationCheckOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete this item? Deleting the item will not affect IIS settings etc. 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_ConfirmDelete {
            get {
                return ResourceManager.GetString("ManagedItemSettings_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to revoke this certificate? 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_ConfirmRevokeCertificate {
            get {
                return ResourceManager.GetString("ManagedItemSettings_ConfirmRevokeCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display Name: 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_DisplayName {
            get {
                return ResourceManager.GetString("ManagedItemSettings_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Domain 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_Domain {
            get {
                return ResourceManager.GetString("ManagedItemSettings_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The following selected domains will be included as a single certificate request. The Lets Encrypt service must be able to access all of these domains via port 80 (for HTTP challenges) or port 443 (for TLS-SNI challenges) for the certification process to work. 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_DomainIncluded {
            get {
                return ResourceManager.GetString("ManagedItemSettings_DomainIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Auto Renewal 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_EnableAutoRenewal {
            get {
                return ResourceManager.GetString("ManagedItemSettings_EnableAutoRenewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note: To export this certificate use the Manage Computer Certificates option in Windows.  的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_ExportTip {
            get {
                return ResourceManager.GetString("ManagedItemSettings_ExportTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body: 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_HookBody {
            get {
                return ResourceManager.GetString("ManagedItemSettings_HookBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ContentType: 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_HookContentType {
            get {
                return ResourceManager.GetString("ManagedItemSettings_HookContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method: 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_HookMethod {
            get {
                return ResourceManager.GetString("ManagedItemSettings_HookMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Method for the webhook must be set. 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_HookMethodMustBeSet {
            get {
                return ResourceManager.GetString("ManagedItemSettings_HookMethodMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Url for the webhook must be set to a valid Url. 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_HookMustBeValidUrl {
            get {
                return ResourceManager.GetString("ManagedItemSettings_HookMustBeValidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Webhook Trigger: 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_HookTrigger {
            get {
                return ResourceManager.GetString("ManagedItemSettings_HookTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url: 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_HookUrl {
            get {
                return ResourceManager.GetString("ManagedItemSettings_HookUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_Include {
            get {
                return ResourceManager.GetString("ManagedItemSettings_Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The log file for this item has not been created yet. 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_LogNotCreated {
            get {
                return ResourceManager.GetString("ManagedItemSettings_LogNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A name is required for this item. 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_NameRequired {
            get {
                return ResourceManager.GetString("ManagedItemSettings_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A Primary Domain must be included 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_NeedPrimaryDomain {
            get {
                return ResourceManager.GetString("ManagedItemSettings_NeedPrimaryDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No changes were made, skipping save 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_NoChanges {
            get {
                return ResourceManager.GetString("ManagedItemSettings_NoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are no http or https hostname bindings associated with the selected site in IIS. At least one fully qualified hostname (e.g &apos;github.com&apos;) is required to create a certificate. 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_NoHostNameBindingWarnging {
            get {
                return ResourceManager.GetString("ManagedItemSettings_NoHostNameBindingWarnging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notify Primary Contact On Renewal Failure 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_NotifyPrimaryContactOnRenewalFailure {
            get {
                return ResourceManager.GetString("ManagedItemSettings_NotifyPrimaryContactOnRenewalFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Log File 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_OpenLogFile {
            get {
                return ResourceManager.GetString("ManagedItemSettings_OpenLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Perform challenge response config checks 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_PerformChallengeResponseConfigCheck {
            get {
                return ResourceManager.GetString("ManagedItemSettings_PerformChallengeResponseConfigCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Perform web application auto config 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_PerformWebAppAutoConfig {
            get {
                return ResourceManager.GetString("ManagedItemSettings_PerformWebAppAutoConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pre-request PS Script: 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_PerRequsetScript {
            get {
                return ResourceManager.GetString("ManagedItemSettings_PerRequsetScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post-request PS Script: 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_PostRequestScript {
            get {
                return ResourceManager.GetString("ManagedItemSettings_PostRequestScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Primary 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_Primary {
            get {
                return ResourceManager.GetString("ManagedItemSettings_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Request Certificate 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_RequestCertificate {
            get {
                return ResourceManager.GetString("ManagedItemSettings_RequestCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Revoke Certificate 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_RevokeCertificate {
            get {
                return ResourceManager.GetString("ManagedItemSettings_RevokeCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Revoking Certificate:
        ///{0} 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_RevokeCertificateError {
            get {
                return ResourceManager.GetString("ManagedItemSettings_RevokeCertificateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Domains and Subdomains to include: 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_SelectDomain {
            get {
                return ResourceManager.GetString("ManagedItemSettings_SelectDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select IIS Site: 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_SelectIISSite {
            get {
                return ResourceManager.GetString("ManagedItemSettings_SelectIISSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select None 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_SelectNone {
            get {
                return ResourceManager.GetString("ManagedItemSettings_SelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the website to create a certificate for. 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_SelectWebsiteOrCert {
            get {
                return ResourceManager.GetString("ManagedItemSettings_SelectWebsiteOrCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_Tab_Options {
            get {
                return ResourceManager.GetString("ManagedItemSettings_Tab_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use SNI (IIS 8+): 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_UseSNI {
            get {
                return ResourceManager.GetString("ManagedItemSettings_UseSNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use specific IP/Port bindings 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_UseSpecificBinding {
            get {
                return ResourceManager.GetString("ManagedItemSettings_UseSpecificBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Certificate 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_ViewCertificate {
            get {
                return ResourceManager.GetString("ManagedItemSettings_ViewCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Webhook request error: {0} 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_WebhookRequestError {
            get {
                return ResourceManager.GetString("ManagedItemSettings_WebhookRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Webhook request {0}: HTTP {1} 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_WebhookRequestResult {
            get {
                return ResourceManager.GetString("ManagedItemSettings_WebhookRequestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Webhook Test 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_WebhookTest {
            get {
                return ResourceManager.GetString("ManagedItemSettings_WebhookTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Webhook Test Failed 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_WebhookTestFailed {
            get {
                return ResourceManager.GetString("ManagedItemSettings_WebhookTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Website Root Directory 的本地化字符串。
        /// </summary>
        public static string ManagedItemSettings_WebsiteRoot {
            get {
                return ResourceManager.GetString("ManagedItemSettings_WebsiteRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter... 的本地化字符串。
        /// </summary>
        public static string ManagedSites_Filter {
            get {
                return ResourceManager.GetString("ManagedSites_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Free SSL Certificates provided via the Let&apos;s Encrypt service (https://letsencrypt.org). 的本地化字符串。
        /// </summary>
        public static string ManagedSites_NoItemSelectedDesc {
            get {
                return ResourceManager.GetString("ManagedSites_NoItemSelectedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a Managed Site or select New Certificate to begin. 的本地化字符串。
        /// </summary>
        public static string ManagedSites_NoItemSelectedTip {
            get {
                return ResourceManager.GetString("ManagedSites_NoItemSelectedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have unsaved changes. Save or Discard your changes before proceeding. 的本地化字符串。
        /// </summary>
        public static string ManagedSites_UnsavedWarning {
            get {
                return ResourceManager.GetString("ManagedSites_UnsavedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Certificate 的本地化字符串。
        /// </summary>
        public static string New_Certificate {
            get {
                return ResourceManager.GetString("New_Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Contact 的本地化字符串。
        /// </summary>
        public static string New_Contact {
            get {
                return ResourceManager.GetString("New_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ooops, you forgot to provide a valid email address. 的本地化字符串。
        /// </summary>
        public static string New_Contact_EmailError {
            get {
                return ResourceManager.GetString("New_Contact_EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You need to agree to the latest LetsEncrypt.org Subscriber Agreement. 的本地化字符串。
        /// </summary>
        public static string New_Contact_NeedAgree {
            get {
                return ResourceManager.GetString("New_Contact_NeedAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To use Certify and the free Let&apos;s Encrypt service to acquire SSL certificates you must first register as a contact. 的本地化字符串。
        /// </summary>
        public static string New_Contact_Tip1 {
            get {
                return ResourceManager.GetString("New_Contact_Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The email address provided may be used to notify you of upcoming certificate renewals if required. Invalid email addresses will be rejected by Let&apos;s Encrypt. 的本地化字符串。
        /// </summary>
        public static string New_Contact_Tip2 {
            get {
                return ResourceManager.GetString("New_Contact_Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you agree to the LetsEncrypt.org Subscriber Agreement? Refer to their website for full details before proceeding. https://letsencrypt.org/repository/ 的本地化字符串。
        /// </summary>
        public static string NewContact_AgreeConfirm {
            get {
                return ResourceManager.GetString("NewContact_AgreeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are no requests currently in progress. 的本地化字符串。
        /// </summary>
        public static string ProgressMonitor_NoProgress {
            get {
                return ResourceManager.GetString("ProgressMonitor_NoProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register Contact 的本地化字符串。
        /// </summary>
        public static string Register_Contact {
            get {
                return ResourceManager.GetString("Register_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registration 的本地化字符串。
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was a problem trying to validate your license key. Please try again or contact support. 的本地化字符串。
        /// </summary>
        public static string Registration_KeyValidationError {
            get {
                return ResourceManager.GetString("Registration_KeyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the email address you used when registering your key. 的本地化字符串。
        /// </summary>
        public static string Registration_NeedEmail {
            get {
                return ResourceManager.GetString("Registration_NeedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your license key. 的本地化字符串。
        /// </summary>
        public static string Registration_NeedKey {
            get {
                return ResourceManager.GetString("Registration_NeedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was a problem beginning the license validation process. 的本地化字符串。
        /// </summary>
        public static string Registration_UnableToVerify {
            get {
                return ResourceManager.GetString("Registration_UnableToVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registered Email Address 的本地化字符串。
        /// </summary>
        public static string RegistrationEmailAddress {
            get {
                return ResourceManager.GetString("RegistrationEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Renew All 的本地化字符串。
        /// </summary>
        public static string Renew_All {
            get {
                return ResourceManager.GetString("Renew_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Changes 的本地化字符串。
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Error 的本地化字符串。
        /// </summary>
        public static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The auto renewal task is already configured. If required you can change the admin user account used to execute the task. 的本地化字符串。
        /// </summary>
        public static string ScheduledTaskConfig_AlreadyConfiged {
            get {
                return ResourceManager.GetString("ScheduledTaskConfig_AlreadyConfiged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to create scheduled task with given credentials 的本地化字符串。
        /// </summary>
        public static string ScheduledTaskConfig_FailedToCreateTask {
            get {
                return ResourceManager.GetString("ScheduledTaskConfig_FailedToCreateTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please provide the username and password for an admin level user. 的本地化字符串。
        /// </summary>
        public static string ScheduledTaskConfig_PleaseProvideCredential {
            get {
                return ResourceManager.GetString("ScheduledTaskConfig_PleaseProvideCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scheduled task created 的本地化字符串。
        /// </summary>
        public static string ScheduledTaskConfig_TaskCreated {
            get {
                return ResourceManager.GetString("ScheduledTaskConfig_TaskCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To perform auto renewal of certificates, Certify will create a task in the Windows Task Scheduler. This task needs to run as an Admin level user in order to do certificate management and IIS management tasks. 的本地化字符串。
        /// </summary>
        public static string ScheduledTaskConfig_Tip {
            get {
                return ResourceManager.GetString("ScheduledTaskConfig_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username (DOMAIN\User) 的本地化字符串。
        /// </summary>
        public static string ScheduledTaskConfig_UserNameLabel {
            get {
                return ResourceManager.GetString("ScheduledTaskConfig_UserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure Auto Renewal 的本地化字符串。
        /// </summary>
        public static string ScheduledTaskConfig_WindowTitle {
            get {
                return ResourceManager.GetString("ScheduledTaskConfig_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select All 的本地化字符串。
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send 的本地化字符串。
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Feedback 的本地化字符串。
        /// </summary>
        public static string Send_Feedback {
            get {
                return ResourceManager.GetString("Send_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your Email Address (if you would like a response): 的本地化字符串。
        /// </summary>
        public static string Send_Feedback_Email {
            get {
                return ResourceManager.GetString("Send_Feedback_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorry, there was a problem submitting your feedback. 的本地化字符串。
        /// </summary>
        public static string Send_Feedback_Error {
            get {
                return ResourceManager.GetString("Send_Feedback_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oops, something went wrong. Please tell us about it. 的本地化字符串。
        /// </summary>
        public static string Send_Feedback_Exception {
            get {
                return ResourceManager.GetString("Send_Feedback_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you have any suggestions? 的本地化字符串。
        /// </summary>
        public static string Send_Feedback_Quest {
            get {
                return ResourceManager.GetString("Send_Feedback_Quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thanks, your feedback has now been submitted. 的本地化字符串。
        /// </summary>
        public static string Send_Feedback_Success {
            get {
                return ResourceManager.GetString("Send_Feedback_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your feedback is important to us. Please let us know how we can improve. 的本地化字符串。
        /// </summary>
        public static string Send_Feedback_Tip {
            get {
                return ResourceManager.GetString("Send_Feedback_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Renewal Interval (Days) 的本地化字符串。
        /// </summary>
        public static string Settings_AutoRenewalInterval {
            get {
                return ResourceManager.GetString("Settings_AutoRenewalInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum Auto Renewal Requests Per Session (0 = Unlimited) 的本地化字符串。
        /// </summary>
        public static string Settings_AutoRenewalRequestLimit {
            get {
                return ResourceManager.GetString("Settings_AutoRenewalRequestLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for updates automatically 的本地化字符串。
        /// </summary>
        public static string Settings_CheckUpdates {
            get {
                return ResourceManager.GetString("Settings_CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable DNS Validations checks (Resolution, CAA, DNSSEC) 的本地化字符串。
        /// </summary>
        public static string Settings_EnableDnsValidation {
            get {
                return ResourceManager.GetString("Settings_EnableDnsValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Encrypted File System (EFS) for sensitive files. This option does not work on all versions of Windows. 的本地化字符串。
        /// </summary>
        public static string Settings_EnableEFS {
            get {
                return ResourceManager.GetString("Settings_EnableEFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable proxy API for domain config checks 的本地化字符串。
        /// </summary>
        public static string Settings_EnableProxyApiForDomainConfig {
            get {
                return ResourceManager.GetString("Settings_EnableProxyApiForDomainConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable app telemetry (feature usage reporting) 的本地化字符串。
        /// </summary>
        public static string Settings_EnableTelemetry {
            get {
                return ResourceManager.GetString("Settings_EnableTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore stopped IIS sites for new certificates and renewals 的本地化字符串。
        /// </summary>
        public static string Settings_IgnoreStoppedSites {
            get {
                return ResourceManager.GetString("Settings_IgnoreStoppedSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Primary Contact: 的本地化字符串。
        /// </summary>
        public static string Settings_PrimaryContact {
            get {
                return ResourceManager.GetString("Settings_PrimaryContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 succeeded 的本地化字符串。
        /// </summary>
        public static string succeed {
            get {
                return ResourceManager.GetString("succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test 的本地化字符串。
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Available 的本地化字符串。
        /// </summary>
        public static string Update_Available {
            get {
                return ResourceManager.GetString("Update_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are using the latest version. 的本地化字符串。
        /// </summary>
        public static string UpdateCheckLatestVersion {
            get {
                return ResourceManager.GetString("UpdateCheckLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validate Key 的本地化字符串。
        /// </summary>
        public static string ValidateKey {
            get {
                return ResourceManager.GetString("ValidateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes, I Agree 的本地化字符串。
        /// </summary>
        public static string Yes_I_Agree {
            get {
                return ResourceManager.GetString("Yes_I_Agree", resourceCulture);
            }
        }
    }
}
