//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Certify {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreSR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreSR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Certify.CoreSR", typeof(CoreSR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Certificate Request was aborted by PS script 的本地化字符串。
        /// </summary>
        internal static string CertificateRequestWasAbortedByPSScript {
            get {
                return ResourceManager.GetString("CertificateRequestWasAbortedByPSScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performing Automated Certificate Binding 的本地化字符串。
        /// </summary>
        internal static string CertifyManager_AutoBinding {
            get {
                return ResourceManager.GetString("CertifyManager_AutoBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automated configuration checks failed. Authorizations will not be able to complete.
        ///Check you have http bindings for your site and ensure you can browse to http://{0}/.well-known/acme-challenge/configcheck before proceeding. 的本地化字符串。
        /// </summary>
        internal static string CertifyManager_AutomateConfigurationCheckFailed_HTTP {
            get {
                return ResourceManager.GetString("CertifyManager_AutomateConfigurationCheckFailed_HTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automated configuration checks failed. Authorizations will not be able to complete.
        ///Check you have https SNI bindings for your site
        ///(ex: &apos;0123456789ABCDEF0123456789ABCDEF.0123456789ABCDEF0123456789ABCDEF.acme.invalid&apos;) before proceeding. 的本地化字符串。
        /// </summary>
        internal static string CertifyManager_AutomateConfigurationCheckFailed_SNI {
            get {
                return ResourceManager.GetString("CertifyManager_AutomateConfigurationCheckFailed_SNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Certificate created ready for manual binding: {0} 的本地化字符串。
        /// </summary>
        internal static string CertifyManager_CertificateCreatedForBinding {
            get {
                return ResourceManager.GetString("CertifyManager_CertificateCreatedForBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Certificate installed and SSL bindings updated for {0} 的本地化字符串。
        /// </summary>
        internal static string CertifyManager_CertificateInstalledAndBindingUpdated {
            get {
                return ResourceManager.GetString("CertifyManager_CertificateInstalledAndBindingUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred installing the certificate. Certificate file may not be valid: {0} 的本地化字符串。
        /// </summary>
        internal static string CertifyManager_CertificateInstallFailed {
            get {
                return ResourceManager.GetString("CertifyManager_CertificateInstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Completed Certificate Request. 的本地化字符串。
        /// </summary>
        internal static string CertifyManager_CompleteRequest {
            get {
                return ResourceManager.GetString("CertifyManager_CompleteRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Completed certificate request and automated bindings update (IIS) 的本地化字符串。
        /// </summary>
        internal static string CertifyManager_CompleteRequestAndUpdateBinding {
            get {
                return ResourceManager.GetString("CertifyManager_CompleteRequestAndUpdateBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not begin authorization for domain with Let&apos;s Encrypt: {0}  的本地化字符串。
        /// </summary>
        internal static string CertifyManager_DomainValidationCannotStart {
            get {
                return ResourceManager.GetString("CertifyManager_DomainValidationCannotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Domain validation completed: {0} 的本地化字符串。
        /// </summary>
        internal static string CertifyManager_DomainValidationCompleted {
            get {
                return ResourceManager.GetString("CertifyManager_DomainValidationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Domain validation failed: {0} 
        ///{1} 的本地化字符串。
        /// </summary>
        internal static string CertifyManager_DomainValidationFailed {
            get {
                return ResourceManager.GetString("CertifyManager_DomainValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Domain already has current authorization, skipping verification: {0} 的本地化字符串。
        /// </summary>
        internal static string CertifyManager_DomainValidationSkipVerifed {
            get {
                return ResourceManager.GetString("CertifyManager_DomainValidationSkipVerifed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed prerequisite configuration checks ({0}) 的本地化字符串。
        /// </summary>
        internal static string CertifyManager_FailedPrerequisiteCheck {
            get {
                return ResourceManager.GetString("CertifyManager_FailedPrerequisiteCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Let&apos;s Encrypt service did not issue a valid certificate in the time allowed. {0} 的本地化字符串。
        /// </summary>
        internal static string CertifyManager_LetsEncryptServiceTimeout {
            get {
                return ResourceManager.GetString("CertifyManager_LetsEncryptServiceTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performing Challenge Response via IIS: {0}  的本地化字符串。
        /// </summary>
        internal static string CertifyManager_PerformingChallengeResponseViaIISX0 {
            get {
                return ResourceManager.GetString("CertifyManager_PerformingChallengeResponseViaIISX0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performing Config Tests 的本地化字符串。
        /// </summary>
        internal static string CertifyManager_PerformingConfigTests {
            get {
                return ResourceManager.GetString("CertifyManager_PerformingConfigTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registering Domain Identifiers 的本地化字符串。
        /// </summary>
        internal static string CertifyManager_RegisterDomainIdentity {
            get {
                return ResourceManager.GetString("CertifyManager_RegisterDomainIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registering and Validating {0}  的本地化字符串。
        /// </summary>
        internal static string CertifyManager_RegisteringAndValidatingX0 {
            get {
                return ResourceManager.GetString("CertifyManager_RegisteringAndValidatingX0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requesting Validation from Let&apos;s Encrypt: {0} 的本地化字符串。
        /// </summary>
        internal static string CertifyManager_ReqestValidationFromLetsEncrypt {
            get {
                return ResourceManager.GetString("CertifyManager_ReqestValidationFromLetsEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requesting Certificate via Lets Encrypt 的本地化字符串。
        /// </summary>
        internal static string CertifyManager_RequestCertificate {
            get {
                return ResourceManager.GetString("CertifyManager_RequestCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: Request failed - {1} {2} 的本地化字符串。
        /// </summary>
        internal static string CertifyManager_RequestFailed {
            get {
                return ResourceManager.GetString("CertifyManager_RequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Site stopped (or not present), renewal skipped as domain validation cannot be performed.  的本地化字符串。
        /// </summary>
        internal static string CertifyManager_SiteStopped {
            get {
                return ResourceManager.GetString("CertifyManager_SiteStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skipping Renewal, existing certificate still OK.  的本地化字符串。
        /// </summary>
        internal static string CertifyManager_SkipRenewalOk {
            get {
                return ResourceManager.GetString("CertifyManager_SkipRenewalOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validation of the required challenges did not complete successfully. {0} 的本地化字符串。
        /// </summary>
        internal static string CertifyManager_ValidationForChallengeNotSuccess {
            get {
                return ResourceManager.GetString("CertifyManager_ValidationForChallengeNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finish 的本地化字符串。
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local IIS, SSL Certificate via Let&apos;s Encrypt 的本地化字符串。
        /// </summary>
        internal static string ManagedItemType_LocalIIS {
            get {
                return ResourceManager.GetString("ManagedItemType_LocalIIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual SSL Certificate via Let&apos;s Encrypt 的本地化字符串。
        /// </summary>
        internal static string ManagedItemType_Manual {
            get {
                return ResourceManager.GetString("ManagedItemType_Manual", resourceCulture);
            }
        }
    }
}
