//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Certify.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Certify.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 63154103-66ba-4636-8c6b-7081084daa0e.
        /// </summary>
        internal static string AIInstrumentationKey {
            get {
                return ResourceManager.GetString("AIInstrumentationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certify (Alpha Version).
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://certify.webprofusion.com/downloads/version.json.
        /// </summary>
        internal static string AppUpdateCheckURI {
            get {
                return ResourceManager.GetString("AppUpdateCheckURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://certify.webprofusion.com.
        /// </summary>
        internal static string AppWebsiteURL {
            get {
                return ResourceManager.GetString("AppWebsiteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: This software is a pre-release version for testing and feedback purposes. You should expect bugs. Do not rely on this software for important production sites..
        /// </summary>
        internal static string BetaWarning {
            get {
                return ResourceManager.GetString("BetaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Software is provided &quot;as is&quot; without warranty of any kind, either express or implied, including without limitation any implied warranties of condition, uninterrupted use, merchantability, fitness for a particular purpose, or non-infringement.
        ///
        ///Use of the LetsEncrypt.org service for free SSL certificates is subject to the LetsEncrypt.org terms of service. This software is not affiliated with or endorsed by LetsEncrypt.org
        ///
        ///This software uses the following Open Source software (or significant portions [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started: Browse the Vault on the left to see current certificate information..
        /// </summary>
        internal static string GettingStartedExistingVault {
            get {
                return ResourceManager.GetString("GettingStartedExistingVault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version = &quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        /// &lt;configuration&gt;
        ///     &lt;system.webServer&gt;
        ///          &lt;staticContent&gt;
        ///	        &lt;mimeMap fileExtension=&quot;.*&quot; mimeType=&quot;text/plain&quot; /&gt;
        ///	        
        ///   &lt;/staticContent&gt;
        ///     &lt;/system.webServer&gt;
        /// &lt;/configuration&gt;.
        /// </summary>
        internal static string IISWebConfig {
            get {
                return ResourceManager.GetString("IISWebConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version = &quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        /// &lt;configuration&gt;
        ///     &lt;system.webServer&gt;
        ///          &lt;staticContent&gt;
        ///	        &lt;mimeMap fileExtension=&quot;.&quot; mimeType=&quot;text/plain&quot; /&gt;
        ///   &lt;/staticContent&gt;
        ///     &lt;/system.webServer&gt;
        /// &lt;/configuration&gt;.
        /// </summary>
        internal static string IISWebConfigAlt {
            get {
                return ResourceManager.GetString("IISWebConfigAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certify - SSL Certificate Manager (Alpha Version).
        /// </summary>
        internal static string LongAppName {
            get {
                return ResourceManager.GetString("LongAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20160327.Alpha9.
        /// </summary>
        internal static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using the latest version..
        /// </summary>
        internal static string UpdateCheckLatestVersion {
            get {
                return ResourceManager.GetString("UpdateCheckLatestVersion", resourceCulture);
            }
        }
    }
}
