<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <EnableMSTestRunner>true</EnableMSTestRunner>
        <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
        <ValidateExecutableReferencesMatchSelfContained>false</ValidateExecutableReferencesMatchSelfContained>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.4">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
        <PackageReference Include="Moq" Version="4.20.72" />
        <PackageReference Include="MSTest.TestAdapter" Version="3.10.4" />
        <PackageReference Include="MSTest.TestFramework" Version="3.10.4" />
        <PackageReference Include="MedallionShell" Version="1.6.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Certify.CLI\Certify.CLI.csproj" />
        <ProjectReference Include="..\..\Certify.Server\Certify.Server.Core\Certify.Server.Core\Certify.Server.Core.csproj" />
    </ItemGroup>
</Project>
