name: certify-core-tests-unit-win
services:

  certify-core-tests-unit-9_0:
    image: certify-core-tests-unit-9_0-win:latest
    build: 
      context: ../../../../
      dockerfile: ./certify/src/Certify.Tests/Certify.Core.Tests.Unit/certify-core-tests-unit-9_0-win.dockerfile
    # environment:
    #   VSTEST_HOST_DEBUG: 1
    ports:
      - 80:80
      - 443:443
      - 9696:9696
    # entrypoint: "dotnet test Certify.Core.Tests.Unit.dll -f net9.0 --filter 'ClassName=Certify.Core.Tests.Unit.CertifyManagerAccountTests'"
    # entrypoint: "dotnet test Certify.Core.Tests.Unit.dll -f net9.0 --filter 'Name=TestCertifyManagerGetAccountDetailsDefinedCertificateAuthorityId'"
    volumes:
      - step:C:\step_share
    profiles: ["9_0"]
    depends_on:
      step-ca:
        condition: service_healthy

  certify-core-tests-unit-4_6_2:
    image: certify-core-tests-unit-4_6_2-win:latest
    build: 
      context: ../../../../
      dockerfile: ./certify/src/Certify.Tests/Certify.Core.Tests.Unit/certify-core-tests-unit-4_6_2-win.dockerfile
    # environment:
    #   VSTEST_HOST_DEBUG: 1
    ports:
      - 80:80
      - 443:443
      - 9696:9696
    # entrypoint: "dotnet test Certify.Core.Tests.Unit.dll -f net462 --filter 'ClassName=Certify.Core.Tests.Unit.CertifyManagerAccountTests'"
    # entrypoint: "dotnet test Certify.Core.Tests.Unit.dll -f net462 --filter 'Name=TestCertifyManagerGetAccountDetailsDefinedCertificateAuthorityId'"
    volumes:
      - step:C:\step_share
    profiles: ["4_6_2"]
    depends_on:
      step-ca:
        condition: service_healthy
  
  step-ca:
    image: step-ca-win:latest
    build: 
      context: .
      dockerfile: ./step-ca-win.dockerfile   
    hostname: step-ca
    profiles: ["4_6_2", "9_0"]
    ports:
      - 9000:9000
    environment:
      DOCKER_STEPCA_INIT_NAME: Smallstep
      DOCKER_STEPCA_INIT_DNS_NAMES: localhost
      DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT: true
      DOCKER_STEPCA_INIT_ACME: true
    volumes:
      - step:C:\Users\ContainerUser\.step

volumes:
  step: {}
